// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int N = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;

		for (int i = 0; i < N; i++) {
			double num = Math.random();

		if (num > 0.5) {
			big = big + 1;
		}
		else {
			small = small + 1;

			}
		}
		if (small > 0) {
			System.out.println("> 0.5: " + big + " times");
			System.out.println("<= 0.5: " + small + " times");
			System.out.println("Ratio: " + (big / (double)small));
		}

		else {
			System.out.println("> 0.5: " + big + " times");
			System.out.println("<= 0.5: " + small + " times");

			}
		}
	}

